### ISSUE TITLE
Getting timeout when adding document to Redisearch

### ISSUE THREAD

**Issue by oruchreis** [JohnSully/KeyDB#27]
Hi,
I'm trying to use redisearch with keydb. Afaik, keydb supports modules. I can create indices but I get timeout when adding document. You can reproduce this issue with these codes:
```
root@keydb-0:/data# keydb-cli
127.0.0.1:6379> FT.CREATE idx SCHEMA id NUMERIC SORTABLE name TEXT SORTABLE
OK
127.0.0.1:6379> FT.ADD idx 1 1.0 FIELDS id 1 name 'NameTest'

```

**Comment by JohnSully** [comment]
We definitely support modules including search. I will investigate.

**Comment by JohnSully** [comment]
Is your keydb instance crashing?  I'm seeing a very interesting bug caused by returning unaligned pointers from malloc.

**Comment by JohnSully** [comment]
I fixed two bugs, one related to loading modules which it looks like you did not hit, and the unaligned malloc issue.  I could not reproduce the timeout (unless it was caused by the unaligned crash).

Current fixes are in both the unstable and RELEASE_0_9 branches, docker will take a bit of time to update.  

If your issue still repros I'd love to debug this further with you.

**Comment by oruchreis** [comment]
Sorry for late response, I'm using keydb in azure aks with docker image. I'll try it right now.

**Comment by oruchreis** [comment]
I've tested with latest image which is 0.9.4-r3 as I see. The problem still exists in this version. Here are the stdout logs if it helps:
```

14:C 24 Apr 2019 06:40:16.882 # oO0OoO0OoO0Oo KeyDB is starting oO0OoO0OoO0Oo
14:C 24 Apr 2019 06:40:16.882 # KeyDB version=0.9.4-r3, bits=64, commit=71531287, modified=0, pid=14, just started
14:C 24 Apr 2019 06:40:16.882 # Configuration loaded
14:M 24 Apr 2019 06:40:16.883 * Running mode=standalone, port=6379.
14:M 24 Apr 2019 06:40:16.883 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
14:M 24 Apr 2019 06:40:16.883 # Server initialized
14:M 24 Apr 2019 06:40:16.884 * <ft> Low level api version 1 initialized successfully
14:M 24 Apr 2019 06:40:16.884 * <ft> RediSearch version 1.4.2 (Git=v1.4.2-281-g69f11baa)
14:M 24 Apr 2019 06:40:16.884 * <ft> concurrency: ON, gc: ON, prefix min length: 2, prefix max expansions: 200, query timeout (ms): 500, timeout policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 1000000, search pool size: 20, index pool size: 8, 
14:M 24 Apr 2019 06:40:16.885 * <ft> Initialized thread pool!
14:M 24 Apr 2019 06:40:16.885 * Module 'ft' loaded from /data/redisearch.so
14:M 24 Apr 2019 06:40:16.947 * Loading RDB produced by version 0.9.3
14:M 24 Apr 2019 06:40:16.947 * RDB age 611458 seconds
14:M 24 Apr 2019 06:40:16.947 * RDB memory usage when created 20.19 Mb
14:M 24 Apr 2019 06:40:17.218 * DB loaded from disk: 0.333 seconds
14:M 24 Apr 2019 06:40:17.218 * Ready to accept connections
14:M 24 Apr 2019 06:40:17.218 d Thread 1 alive.
14:M 24 Apr 2019 06:40:17.218 d Thread 2 alive.
14:M 24 Apr 2019 06:40:17.218 d Thread 0 alive.
14:M 24 Apr 2019 06:40:17.218 d Thread 3 alive.
14:M 24 Apr 2019 06:42:16.369 * Replica 10.90.70.53:6379 asks for synchronization
14:M 24 Apr 2019 06:42:16.369 * Partial resynchronization not accepted: Replication ID mismatch (Replica asked for '9c3e31e8ea3a3a5a9381eb7721086d530fe725c3', my replication IDs are '51c4665675d28ec82134d565ad590380bf6b7a88' and '0000000000000000000000000000000000000000')
14:M 24 Apr 2019 06:42:16.369 * Starting BGSAVE for SYNC with target: disk
14:M 24 Apr 2019 06:42:16.370 * Background saving started by pid 378
378:C 24 Apr 2019 06:42:16.674 * DB saved on disk
378:C 24 Apr 2019 06:42:16.676 * RDB: 1 MB of memory used by copy-on-write
14:M 24 Apr 2019 06:42:16.749 * Background saving terminated with success
14:M 24 Apr 2019 06:42:16.796 * Synchronization with replica 10.90.70.53:6379 succeeded
```

**Comment by JohnSully** [comment]
Thanks it appears you do have some features enabled I did not test with.  I've been able to reproduce the issue.  I'll update this thread when I have a fix.

**Comment by JohnSully** [comment]
Just an update as this is taking longer than expected - there's a negative interaction with the multithreading in RediSearch and in KeyDB.  It seems to be related to some Redis code I pulled in a little while back.  I'm still working on a fix.

For now the only workaround I have is to run KeyDB single threaded... but that definitely takes all the fun out of it.

**Comment by oruchreis** [comment]
I perefer using keydb with multi-threaded over redisearch. We can implement our index structures with using classical redis types as a workaround until keydb supports redisearch. Thanks for your support.

**Comment by JohnSully** [comment]
Fixed in change bf26959b7.  Please let me know if you have any more issues (unfortunately RediSearch no longer ships with a test suite).

**Comment by JohnSully** [comment]
This has been included in the v0.9.5 release available on docker.  Please reopen if you see further issues.
